#
# Makefile for industrial I/O potentiometer drivers
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_MCP4531) += mcp4531.o

#100ask expansion board ds18b20 module driver
obj-$(CONFIG_DS18B20_MOD) += 100ask_ds18b20.o
